# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_itemmodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='Item',
        ),
    ]
